export const constants = {
	ADD_USER: "ADD_USER",
	ADD_DOOR: "ADD_DOOR",
	REMOVE_USER: "REMOVE_USER",
	UPDATE_USER: "UPDATE_USER",
	REMOVE_DOOR: "REMOVE_DOOR",
	ACCESS_DOOR: "ACCESS_DOOR",
	LOG_ITEM: "LOG_ITEM",
	TOGGLE_ALERT: "TOGGLE_ALERT",
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT"
};
